new picom

diff --git a/bin/SOS_Wifi_Menu b/bin/SOS_Wifi_Menu
--- a/bin/SOS_Wifi_Menu
+++ b/bin/SOS_Wifi_Menu
@@ -7,102 +7,109 @@
 # SpectrumOS - Embrace the Chromatic Symphony!
 # By: gibranlp <thisdoesnotwork@gibranlp.dev>
 # MIT licence 
-# 
-#
 
-# Starts a scan of available broadcasting SSIDs
-# nmcli dev wifi rescan
-
+# Constants
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+FIELDS="SSID,SECURITY"
+FONT="Courier Prime Medium 13"
+ROFI_THEME="$HOME/.config/rofi/SOS_Wifi.rasi"
 
-FIELDS=SSID,SECURITY
-POSITION=0
-YOFF=0
-XOFF=0
-FONT="Fira Code Medium 13"
-
+# Load configuration
 if [ -r "$DIR/config" ]; then
-	source "$DIR/config"
+    source "$DIR/config"
 elif [ -r "$HOME/.config/rofi/wifi" ]; then
-	source "$HOME/.config/rofi/wifi"
+    source "$HOME/.config/rofi/wifi"
 else
-	echo "WARNING: config file not found! Using default values."
+    echo "WARNING: config file not found! Using default values."
 fi
 
-LIST=$(nmcli --fields "$FIELDS" device wifi list | sed '/^--/d')
-# For some reason rofi always approximates character width 2 short... hmmm
-RWIDTH=$(($(echo "$LIST" | head -n 1 | awk '{print length($0); }')+2))
-# Dynamically change the height of the rofi menu
-LINENUM=$(echo "$LIST" | wc -l)
-# Gives a list of known connections so we can parse it later
-KNOWNCON=$(nmcli connection show)
-# Really janky way of telling if there is currently a connection
-CONSTATE=$(nmcli -fields WIFI g)
+# Function to show the menu and handle user input
+show_menu() {
+    # List available WiFi devices
+    DEVICES=$(nmcli device | awk '$2 == "wifi" {print $1, $3}' | sort)
+    SELECTED_DEVICE=$(echo "$DEVICES" | rofi -theme "$ROFI_THEME" -dmenu -p "Select WiFi Device:" -font "$FONT" -lines 10 | awk '{print $1}')
 
-CURRSSID=$(LANGUAGE=C nmcli -t -f active,ssid dev wifi | awk -F: '$1 ~ /^yes/ {print $2}')
+    if [ -z "$SELECTED_DEVICE" ]; then
+        echo "No WiFi device selected. Exiting."
+        exit 1
+    fi
 
-if [[ ! -z $CURRSSID ]]; then
-	HIGHLINE=$(echo  "$(echo "$LIST" | awk -F "[  ]{2,}" '{print $1}' | grep -Fxn -m 1 "$CURRSSID" | awk -F ":" '{print $1}') + 1" | bc )
-fi
+    # Get available WiFi networks for the selected device
+    LIST=$(nmcli --fields "$FIELDS" device wifi list ifname "$SELECTED_DEVICE" | sed '/^--/d')
+    RWIDTH=$(( $(echo "$LIST" | awk '{print length($0)}' | sort -nr | head -n1) + 2 ))
+    LINENUM=$(echo "$LIST" | wc -l)
+    KNOWNCON=$(nmcli connection show)
+    CONSTATE=$(nmcli -fields WIFI g)
+    CURRSSID=$(nmcli -t -f active,ssid dev wifi ifname "$SELECTED_DEVICE" | awk -F: '$1 ~ /^yes/ {print $2}')
 
-if [ "$LINENUM" -gt 8 ] && [[ "$CONSTATE" =~ "enabled" ]]; then
-	LINENUM=8
-elif [[ "$CONSTATE" =~ "disabled" ]]; then
-	LINENUM=1
-fi
+    # Determine highline for currently connected SSID
+    if [ -n "$CURRSSID" ]; then
+        HIGHLINE=$(echo "$LIST" | awk -F"[[:space:]]{2,}" -v ssid="$CURRSSID" '$1 == ssid {print NR}' | head -n1)
+    else
+        HIGHLINE=0
+    fi
 
+    # Determine number of lines for rofi menu
+    if [ "$LINENUM" -gt 8 ] && [[ "$CONSTATE" == *"enabled"* ]]; then
+        LINENUM=8
+    elif [[ "$CONSTATE" == *"disabled"* ]]; then
+        LINENUM=1
+    fi
 
-if [[ "$CONSTATE" =~ "enabled" ]]; then
-	TOGGLE=" Toggle Wifi Off"
-elif [[ "$CONSTATE" =~ "disabled" ]]; then
-	TOGGLE=" Toggle Wifi On"
-fi
+    # Toggle WiFi text
+    if [[ "$CONSTATE" == *"enabled"* ]]; then
+        TOGGLE=" Toggle Wifi Off"
+    else
+        TOGGLE=" Toggle Wifi On"
+    fi
 
+    # Show rofi menu
+    CHENTRY=$(echo -e "$TOGGLE\n󰌚 Manual\n$LIST" | uniq -u | rofi -theme "$ROFI_THEME" -dmenu -p "󱛃 Wi-Fi SSID: " -lines "$LINENUM" -a "$HIGHLINE" -location "$POSITION" -yoffset "$YOFF" -xoffset "$XOFF" -font "$FONT" -width -"$RWIDTH")
 
+    # Extract chosen SSID
+    CHSSID=$(echo "$CHENTRY" | sed 's/[[:space:]]\{2,\}/|/g' | awk -F "|" '{print $1}')
 
-CHENTRY=$(echo -e "$TOGGLE\n 󰌚 Manual\n$LIST" | uniq -u | rofi -theme '~/.config/rofi/SOS_Wifi.rasi' -dmenu -p "󱛃 Wi-Fi SSID: " -lines "$LINENUM" -a "$HIGHLINE" -location "$POSITION" -yoffset "$YOFF" -xoffset "$XOFF" -font "$FONT" -width -"$RWIDTH")
-#echo "$CHENTRY"
-CHSSID=$(echo "$CHENTRY" | sed  's/\s\{2,\}/\|/g' | awk -F "|" '{print $1}')
-#echo "$CHSSID"
+    # Handle user input
+    case "$CHENTRY" in
+        " Manual")
+            # Manual entry of SSID and password
+            MSSID=$(echo "Enter  SSID,  Password" | rofi -theme "$ROFI_THEME" -dmenu -p " Manual Entry: " -font "$FONT" -lines 1)
+            MPASS=$(echo "$MSSID" | awk -F "," '{print $2}')
+            
+            if [ -z "$MPASS" ]; then
+                nmcli dev wifi con "$MSSID" ifname "$SELECTED_DEVICE"
+            else
+                nmcli dev wifi con "$MSSID" password "$MPASS" ifname "$SELECTED_DEVICE"
+            fi
+            ;;
+        
+        " Toggle Wifi Off")
+            nmcli radio wifi off ifname "$SELECTED_DEVICE"
+            show_menu  # Return to menu after toggling WiFi off
+            ;;
+        
+        " Toggle Wifi On")
+            nmcli radio wifi on ifname "$SELECTED_DEVICE"
+            show_menu  # Return to menu after toggling WiFi on
+            ;;
+        
+        *)
+            # Check if SSID is already known
+            if [[ "$CHSSID" == "*" ]]; then
+                CHSSID=$(echo "$CHENTRY" | sed 's/[[:space:]]\{2,\}/|/g' | awk -F "|" '{print $3}')
+            fi
+            
+            if echo "$KNOWNCON" | grep -q "$CHSSID"; then
+                nmcli con up "$CHSSID"
+            else
+                if [[ "$CHENTRY" =~ "WPA2" ]] || [[ "$CHENTRY" =~ "WEP" ]]; then
+                    WIFIPASS=$(rofi -theme "$ROFI_THEME" -dmenu -p " Password: " -lines 1 -font "$FONT")
+                fi
+                nmcli dev wifi con "$CHSSID" password "$WIFIPASS" ifname "$SELECTED_DEVICE"
+            fi
+            ;;
+    esac
+}
 
-# If the user inputs "manual" as their SSID in the start window, it will bring them to this screen
-if [ "$CHENTRY" = " Manual" ] ; then
-	# Manual entry of the SSID and password (if appplicable)
-	MSSID=$(echo "Enter  SSID,  Password" | rofi -theme '~/.config/rofi/SOS_Wifi.rasi' -dmenu -p " Manual Entry: " -font "$FONT" -lines 1)
-	# Separating the password from the entered string
-	MPASS=$(echo "$MSSID" | awk -F "," '{print $2}')
-
-	#echo "$MSSID"
-	#echo "$MPASS"
-
-	# If the user entered a manual password, then use the password nmcli command
-	if [ "$MPASS" = "" ]; then
-		nmcli dev wifi con "$MSSID"
-	else
-		nmcli dev wifi con "$MSSID" password "$MPASS"
-	fi
-
-elif [ "$CHENTRY" = "toggle on" ]; then
-	nmcli radio wifi on
-
-elif [ "$CHENTRY" = "toggle off" ]; then
-	nmcli radio wifi off
-
-else
-
-	# If the connection is already in use, then this will still be able to get the SSID
-	if [ "$CHSSID" = "*" ]; then
-		CHSSID=$(echo "$CHENTRY" | sed  's/\s\{2,\}/\|/g' | awk -F "|" '{print $3}')
-	fi
-
-	# Parses the list of preconfigured connections to see if it already contains the chosen SSID. This speeds up the connection process
-	if [[ $(echo "$KNOWNCON" | grep "$CHSSID") = "$CHSSID" ]]; then
-		nmcli con up "$CHSSID"
-	else
-		if [[ "$CHENTRY" =~ "WPA2" ]] || [[ "$CHENTRY" =~ "WEP" ]]; then
-			WIFIPASS=$(echo | rofi -theme '~/.config/rofi/SOS_Wifi.rasi' -dmenu -p " Password: " -lines 1 -font "$FONT" )
-		fi
-		nmcli dev wifi con "$CHSSID" password "$WIFIPASS"
-	fi
-
-fi
+# Show the menu for the first time
+show_menu
